# -*- coding: utf-8 -*-
"""RAMC_Training_Run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLUXawvsmH-bocSjIqluhFTmmmPacW2i
"""

# ============================================================
# Cell 1: Environment Setup
# ============================================================
import torch

print(f"PyTorch version : {torch.__version__}")
print(f"CUDA available  : {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU             : {torch.cuda.get_device_name(0)}")
    free, total = torch.cuda.mem_get_info(0)
    print(f"GPU Memory      : {total / 1e9:.1f} GB  (free: {free / 1e9:.1f} GB)")

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

import os
WORK_DIR = "/content/drive/MyDrive/Colab Notebooks/RAMC NN Training"
os.chdir(WORK_DIR)
print(f"\nWorking directory: {os.getcwd()}")
print("\nFiles in directory:")
for f in sorted(os.listdir('.')):
    size_mb = os.path.getsize(f) / 1e6 if os.path.isfile(f) else 0
    print(f"  {f:<45s} {size_mb:>8.2f} MB" if os.path.isfile(f) else f"  {f}/")

# ============================================================
# Cell 2: Pre-flight checks
#   - Dataset integrity (columns, ranges)
#   - Solar column name cross-check against RCModelDataset
#   - Module imports
#   - Rollout config summary
# ============================================================
import pandas as pd
import numpy as np

CSV_PATH = "RAMC_training_data_N3.csv"
assert os.path.exists(CSV_PATH), f"Dataset not found: {CSV_PATH}"

# ── Column presence ──────────────────────────────────────────
df_head = pd.read_csv(CSV_PATH, nrows=5)
print(f"Dataset columns ({len(df_head.columns)}):")
print(df_head.columns.tolist())

required = [
    'T_air_k', 'T_env_k', 'T_int_k', 'T_rad1_k', 'T_rad2_k', 'T_ret_k',
    'T_supply_k', 'mdot_k', 'T_out_k', 'Q_internal_k',
    'T_air_k1', 'T_env_k1', 'T_int_k1', 'T_rad1_k1', 'T_rad2_k1', 'T_ret_k1',
    'Tmin', 'Tmax', 'Timestamp',
]

# Auto-detect solar column name
solar_col = next(
    (c for c in ['Q_solar_trans_k', 'Q_solar_k', 'I_solar_k'] if c in df_head.columns),
    None,
)
print(f"\nSolar column detected: {solar_col}")

missing = [c for c in required if c not in df_head.columns]
if missing:
    print(f"\nMissing columns: {missing}")
else:
    print("All required columns present")

# ── Data ranges ──────────────────────────────────────────────
usecols = ['Q_internal_k', 'T_out_k', 'Tmin', 'Tmax']
if solar_col:
    usecols.append(solar_col)
df_ranges = pd.read_csv(CSV_PATH, usecols=usecols)

print(f"\nQ_internal_k : [{df_ranges['Q_internal_k'].min():.0f}, {df_ranges['Q_internal_k'].max():.0f}] W")
if solar_col:
    print(f"{solar_col:<13s}: [{df_ranges[solar_col].min():.0f}, {df_ranges[solar_col].max():.0f}] W")
print(f"T_out_k      : [{df_ranges['T_out_k'].min():.1f}, {df_ranges['T_out_k'].max():.1f}] °C")
print(f"Tmin         : [{df_ranges['Tmin'].min():.1f}, {df_ranges['Tmin'].max():.1f}] °C  (ignored during training)")
print(f"Tmax         : [{df_ranges['Tmax'].min():.1f}, {df_ranges['Tmax'].max():.1f}] °C  (ignored during training)")
print("NOTE: comfort_bounds=(20.0, 22.0) is used uniformly (ignore_dataset_bounds=True)")

# ── Solar column cross-check vs RCModelDataset ───────────────
from thermal_dynamics_net import (
    RCModelDataset,
    ThermalDynamicsNet,
    create_dataloaders,
    build_clamp_bounds_from_dataset,
    RolloutSequenceSampler,
)
from trainers import TrainingManager, RAMCTrainer, MSETrainer
from ramc_losses import (
    calculate_ramc_loss,
    evaluate_on_loader,
    compute_rollout_fidelity_loss,
)

expected_solar = RCModelDataset.DISTURBANCE_COLS[1]   # index 1 = solar column
print(f"\nRCModelDataset expects solar column : '{expected_solar}'")
print(f"CSV solar column detected           : '{solar_col}'")

if expected_solar != solar_col:
    print(
        f"\nMISMATCH — update DISTURBANCE_COLS in thermal_dynamics_net.py:\n"
        f"   Change '{expected_solar}' -> '{solar_col}'\n"
        f"   Then re-upload the file and rerun this cell."
    )
    raise SystemExit("Aborting: solar column mismatch.")
else:
    print("Column names match")

print("\nAll imports successful")

# ── Rollout config summary ────────────────────────────────────
from main_experiment import LOSS_CONFIG, LAMBDA_VALUES, EXPERIMENT_MODE

alpha_ro = LOSS_CONFIG.get("alpha_rollout", 0.0)
H_r      = LOSS_CONFIG.get("rollout_horizon", 6)
B_r      = LOSS_CONFIG.get("rollout_batch_size", 64)

print(f"\n{'─'*55}")
print(f"Experiment mode      : {EXPERIMENT_MODE}")
print(f"Lambda grid          : {LAMBDA_VALUES}")
print(f"Rollout fidelity (α) : {alpha_ro}  ({'ENABLED' if alpha_ro > 0 else 'disabled'})")
if alpha_ro > 0:
    print(f"  Rollout horizon H_r: {H_r} steps  ({H_r * 10} min)")
    print(f"  Rollout batch B_r  : {B_r} sequences")
    print(f"  Checkpoint suffix  : _rollout_a{alpha_ro}")
print(f"{'─'*55}")

# ============================================================
# Cell 3: Main Training Run
#   Runs main_experiment.py in-process so all variables (RESULTS_DIR
#   etc.) remain accessible in subsequent cells.
#   Expected runtime: T4 ~4-6 h | A100 ~1.5-2.5 h | V100 ~3-4 h
# ============================================================
import time
import runpy

print("Starting main_experiment.py …")
start_time = time.time()

# runpy.run_path executes the script under __main__ so the
#   `if __name__ == "__main__": main()` guard triggers correctly.
runpy.run_path("main_experiment.py", run_name="__main__")

elapsed = time.time() - start_time
print(f"\n{'='*80}")
print(f"TOTAL TRAINING TIME: {elapsed/3600:.1f} h  ({elapsed/60:.0f} min)")
print(f"{'='*80}")

# ============================================================
# Cell 4: Decomposed Evaluation Table
#   Automatically finds the most recent results directory so no
#   manual path edits are needed between runs.
# ============================================================
import glob

# Auto-detect latest results directory (covers both FULL and SCOUT modes)
results_dirs = sorted(glob.glob("results/RAMC_*"))
if not results_dirs:
    print("No results directory found — has Cell 3 completed successfully?")
    latest_results = None
else:
    latest_results = results_dirs[-1]
    print(f"Results directory : {latest_results}")
    print("\nContents:")
    for f in sorted(os.listdir(latest_results)):
        size_kb = os.path.getsize(os.path.join(latest_results, f)) / 1024
        print(f"  {f:<50s} {size_kb:>8.1f} KB")

if latest_results:
    import Decompose_evaluation as de

    # Override paths to point at this run's output
    de.RESULTS_DIR  = latest_results
    de.CSV_DATA_PATH = CSV_PATH

    # Align perturbation config with training settings
    de.EVAL_LOSS_CONFIG["sigma_Q_internal"]      = LOSS_CONFIG["sigma_Q_internal"]
    de.EVAL_LOSS_CONFIG["num_perturbations"]      = 256   # higher K for evaluation
    de.EVAL_LOSS_CONFIG["ignore_dataset_bounds"]  = True
    de.EVAL_LOSS_CONFIG["comfort_bounds"]         = LOSS_CONFIG["comfort_bounds"]
    de.EVAL_LOSS_CONFIG["energy_cost_rate"]       = LOSS_CONFIG["energy_cost_rate"]
    de.EVAL_LOSS_CONFIG["w_comfort"]              = LOSS_CONFIG["w_comfort"]
    de.EVAL_LOSS_CONFIG["fidelity_weights"]       = LOSS_CONFIG["fidelity_weights"]

    # Sanity checks before running
    print(f"\nFidelity weights : {de.EVAL_LOSS_CONFIG['fidelity_weights']}")
    print(f"CVaR method      : {de.EVAL_LOSS_CONFIG.get('cvar_method', 'NOT SET')}")

    assert de.EVAL_LOSS_CONFIG.get("cvar_method") == "empirical", (
        "cvar_method in Decompose_evaluation.py must be 'empirical'. "
        "Update that file and re-upload."
    )
    assert de.EVAL_LOSS_CONFIG["fidelity_weights"] == [2.0, 1.0, 1.0, 0.5, 0.5, 2.0], (
        "fidelity_weights in Decompose_evaluation.py must be [2.0, 1.0, 1.0, 0.5, 0.5, 2.0]. "
        "Update that file and re-upload."
    )

    df_results = de.generate_decomposed_evaluation_table(
        results_dir      = latest_results,
        csv_data_path    = CSV_PATH,
        model_config     = de.MODEL_CONFIG,
        eval_loss_config = de.EVAL_LOSS_CONFIG,
        data_config      = de.DATA_CONFIG,
        device           = "cuda" if torch.cuda.is_available() else "cpu",
        num_seeds        = 5,
        enable_tail_diagnostics = False,
        tail_file_tag    = "DIAGNOSTIC",
    )
    print("\nDecomposed evaluation complete")
else:
    print("Skipping decomposed evaluation — no results directory.")

# ============================================================
# Cell 5: Pooled Tail-ECDF Analysis
#   Auto-detects every model checkpoint in the results directory.
#   No lambda values are hardcoded — the model list is built
#   entirely from whatever *.pth files are present.
# ============================================================
if latest_results:
    import pooled_ecdf_analysis as ecdf

    # Override paths
    ecdf.RESULTS_DIR  = latest_results
    ecdf.CSV_DATA_PATH = CSV_PATH
    ecdf.OUTPUT_DIR   = latest_results
    ecdf.COST_CONFIG["energy_cost_rate"] = LOSS_CONFIG["energy_cost_rate"]
    ecdf.COST_CONFIG["w_comfort"]        = LOSS_CONFIG["w_comfort"]

    # ── Auto-detect all checkpoint stems ─────────────────────
    pth_stems = sorted(
        f.replace("_best.pth", "")
        for f in os.listdir(latest_results)
        if f.endswith("_best.pth")
    )
    print("Available model checkpoints:")
    for s in pth_stems:
        print(f"  {s}")

    # ── Assign stable display labels ─────────────────────────
    # Label logic: Raw MSE -> fixed label; Fidelity -> fixed label;
    # RAMC -> "RAMC (λ=X)" derived from the checkpoint stem so it
    # is always correct regardless of which lambdas were trained.
    def _stem_to_label(stem: str) -> str:
        if stem.startswith("Raw_MSE"):
            return "Raw MSE"
        if stem.startswith("Fidelity"):
            return "Fidelity (λ=0)"
        # RAMC stems look like: RAMC_lambda_0.001_op_cvar[_rollout_a1.0]
        import re as _re
        m = _re.search(r"RAMC_lambda_([\d.e+-]+)", stem)
        if m:
            lam = float(m.group(1))
            # Format as clean scientific notation
            if lam == 0:
                return "RAMC (λ=0)"
            exp   = int(np.floor(np.log10(lam)))
            coeff = lam / (10 ** exp)
            if abs(coeff - round(coeff)) < 1e-9:
                coeff = int(round(coeff))
                return f"RAMC (λ={coeff}×10^{exp})" if coeff != 1 else f"RAMC (λ=10^{exp})"
            return f"RAMC (λ={lam:.2g})"
        return stem   # fallback: use stem as-is

    models = [(stem, _stem_to_label(stem)) for stem in pth_stems]

    # ── Auto-generate plot styles ─────────────────────────────
    # Fixed palette: Raw MSE = red, Fidelity = blue (dashed),
    # RAMC variants cycle through greens / purples / oranges.
    RAMC_COLORS = [
        "#2ca02c",  # green
        "#9467bd",  # purple
        "#ff7f0e",  # orange
        "#17becf",  # teal
        "#bcbd22",  # yellow-green
        "#8c564b",  # brown
        "#e377c2",  # pink
    ]
    ramc_color_iter = iter(RAMC_COLORS)

    styles = {}
    for stem, label in models:
        if label == "Raw MSE":
            styles[label] = {"color": "#d62728", "linestyle": "-",  "linewidth": 2.5, "alpha": 0.7}
        elif label.startswith("Fidelity"):
            styles[label] = {"color": "#1f77b4", "linestyle": "--", "linewidth": 2.0, "alpha": 0.9}
        else:
            color = next(ramc_color_iter, "#7f7f7f")
            styles[label] = {"color": color, "linestyle": "-", "linewidth": 2.0, "alpha": 1.0}

    ecdf.MODELS_TO_COMPARE = models
    ecdf.PLOT_STYLES       = styles

    print(f"\nComparing {len(models)} models:")
    for stem, label in models:
        print(f"  {label:<35s}  <- {stem}")

    ecdf.main()
    print("\nPooled ECDF analysis complete")
else:
    print("Skipping ECDF analysis — no results directory.")

# ============================================================
# Cell 6: Final Summary
#   Lists every file produced in the results directory with its
#   size.  No hardcoded model names or lambda values.
# ============================================================
print("=" * 80)
print("RAMC TRAINING PIPELINE COMPLETE")
print("=" * 80)

if latest_results:
    print(f"\nAll outputs in: {latest_results}\n")

    all_files = sorted(os.listdir(latest_results))
    for f in all_files:
        fp = os.path.join(latest_results, f)
        size_kb = os.path.getsize(fp) / 1024
        print(f"  {f:<55s} {size_kb:>8.1f} KB")

    print(f"\n{'─'*80}")
    print("KEY FILE TYPES:")
    print(f"{'─'*80}")
    csvs  = [f for f in all_files if f.endswith(".csv")]
    pngs  = [f for f in all_files if f.endswith(".png")]
    jsons = [f for f in all_files if f.endswith(".json")]
    txts  = [f for f in all_files if f.endswith(".txt")]
    pths  = [f for f in all_files if f.endswith(".pth")]

    if csvs:
        print(f"\nTables / CSVs ({len(csvs)}):")
        for f in csvs:
            print(f"  {f}")
    if pngs:
        print(f"\nFigures / PNGs ({len(pngs)}):")
        for f in pngs:
            print(f"  {f}")
    if jsons:
        print(f"\nJSON metrics ({len(jsons)}):")
        for f in jsons:
            print(f"  {f}")
    if txts:
        print(f"\nText reports ({len(txts)}):")
        for f in txts:
            print(f"  {f}")
    if pths:
        print(f"\nModel checkpoints ({len(pths)}):")
        for f in pths:
            print(f"  {f}")
else:
    print("No results directory found.")

